sudo: required
language: python
cache: pip
services:
  - docker
env:
  - ANSIBLE='ansible>=2.3.0,<2.4.0' PROMETHEUS=1.8.2
  - ANSIBLE='ansible>=2.3.0,<2.4.0' PROMETHEUS=2.2.1
  - ANSIBLE='ansible>=2.4.0,<2.5.0' PROMETHEUS=1.8.2
  - ANSIBLE='ansible>=2.4.0,<2.5.0' PROMETHEUS=2.2.1
  - ANSIBLE='ansible>=2.5.0,<2.6.0' PROMETHEUS=1.8.2
  - ANSIBLE='ansible>=2.5.0,<2.6.0' PROMETHEUS=2.2.1
matrix:
  fast_finish: true
install:
  - pip install ${ANSIBLE} 'ansible-lint>=3.4.15' 'molecule==1.25.0' docker git-semver 'testinfra>=1.7.0,<=1.10.1' jmespath
script:
  - ansible-lint tests/playbook.yml
  - molecule test

jobs:
  include:
    - stage: deploy
      script: .travis/auto.sh

stages:
  - test
  - name: deploy
    if: branch = master

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
