---
dist: xenial
sudo: required
language: python
python:
  - 3.5
cache: pip
services:
  - docker
env:
  - ANSIBLE=2.6
  - ANSIBLE=2.7
  - ANSIBLE=2.8
matrix:
  fast_finish: true
install:
  - pip3 install tox-travis git-semver
script:
  - ./.travis/test.sh
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/releaser.sh
  on:
    branch: master
branches:
  only:
    - master
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
