---
- include: preflight.yml

- include: install.yml
  become: true

- include: configure.yml
  become: true

- name: ensure prometheus service is started and enabled
  become: true
  systemd:
    name: prometheus
    state: started
    enabled: true
